server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/AxiosGaming/Microservicios
          search-paths: config-data
  application:
    name: config-service
          
          